version: 2.1
orbs:
    cypress: cypress-io/cypress@3

jobs:
    run-cypress-in-specified-node-version:
        executor:
            name: cypress/default
            node-version: "20.6" # Node.js 버전 설정
        steps:
            - checkout # 코드 체크아웃
            - run:
                  name: Install dependencies
                  command: yarn install # 의존성 설치
            - run:
                  name: Build the Next.js app
                  command: npm run build # 프로덕션 빌드 실행
            - run:
                  name: Start the Next.js app
                  command: npm run start & # 프로덕션 모드로 서버 실행
            - run:
                  name: Wait for server to be ready
                  command: npx wait-on https://ci-cd-flame.vercel.app # 서버가 준비될 때까지 대기
            - cypress/run:
                  browser: chrome # Cypress를 Chrome에서 실행
                  headless: true # 헤드리스 모드로 실행

workflows:
    version: 2
    use-my-orb:
        jobs:
            - run-cypress-in-specified-node-version
