version: 2.1
orbs:
    cypress: cypress-io/cypress@3

jobs:
    build-and-test:
        executor:
            name: cypress/default
            node-version: "20.6" # Node.js 버전 설정
        steps:
            - checkout # 코드 체크아웃
            - run:
                  name: Install dependencies
                  command: yarn install # 의존성 설치
            - run:
                  name: Build the Next.js app
                  command: npm run build # 프로덕션 빌드 실행
            - run:
                  name: Start the Next.js app
                  command: npm run start & # 프로덕션 모드로 서버 실행
            - run:
                  name: Wait for server to be ready
                  command: npx wait-on https://ci-cd-flame.vercel.app # Vercel 배포 주소로 대기
            - cypress/run:
                  browser: chrome # Cypress를 Chrome에서 실행
                  headless: true # 헤드리스 모드로 실행

workflows:
    version: 2
    build_and_test:
        jobs:
            - build-and-test
