version: 2.1

orbs:
    cypress: cypress-io/cypress@3

jobs:
    run-cypress-tests:
        docker:
            - image: cypress/included:latest # Cypress가 포함된 Docker 이미지 사용
        steps:
            - checkout # 코드 체크아웃
            - run:
                  name: Install dependencies
                  command: yarn install # 의존성 설치
            - run:
                  name: Build the Next.js app
                  command: npm run build # 프로덕션 빌드 실행
            - run:
                  name: Start the Next.js app
                  command: npm run start & # 프로덕션 모드로 서버 실행
            - run:
                  name: Wait for server to be ready
                  command: npx wait-on http://localhost:3000 # 앱이 실행될 때까지 대기
            - cypress/install:
                  package-manager: "yarn"
            - cypress/run-tests:
                  start-command: "npm run start" # 이미 서버가 실행되고 있으므로 start-command 필요 없음
                  cypress-command: "npx cypress run" # Cypress 테스트 실행

workflows:
    version: 2
    test:
        jobs:
            - run-cypress-tests
